blank_issues_enabled: false
contact_links:
  - name: OTTAA's Community Support
    url: https://discord.gg/UsYC8nKX
    about: Please join our Discord Community Support channel to engage with us faster.
  - name: OTTAA's Security Bug Bounty
    url: https://www.ottaaproject.com/contacto.php
    about: Please contact inmediately with an email to "support@ottaaproject.com" about "Security/Vulnerability" to be eligible for a bounty up to 2 ETH.
